### PR TITLE
Disable refresh button

### LINKED ISSUE #7: Restrict Stock Refresh Button
Currently the webstie only shows the closing prices of the previous day for each stock. So there is no point in refreshing multiple times a day(As it is a waste of API tokens)
- add a functionality where once the refresh button is pressed it is disabled for the entire day for that user

Feel free to reach out if any doubts while working on this
image

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request

## Title
Add functionality to disable the refresh button for the day after it is pressed

## Description
This PR introduces a feature to disable the "Refresh Prices" button for the rest of the day once it is pressed. This is to prevent unnecessary API calls since the website only shows the closing prices of the previous day, making it inefficient to refresh multiple times a day.

### Key Changes:
- **Local Storage Implementation**: The last refresh date is stored in the browser’s `localStorage` to track whether the refresh button was already pressed for the current day.
- **Refresh Button State Management**: Added logic to disable the refresh button based on the stored date in `localStorage`.
- **User Interface Feedback**: The button will be disabled after pressing, and a message will notify the user that they have already refreshed the prices for the day.

### Detailed Changes:
- In `StockCard` component:
  - **New State Variables**: `isRefreshDisabled` to handle button state.
  - **New Method**: `checkIfRefreshDoneToday()` checks if the user has already refreshed for the current day.
  - **Event Handler**: `handleRefresh()` disables the button, stores the current date in `localStorage`, and triggers the parent handler to refresh the stock data.
  - **UI Enhancements**: When the button is disabled, it shows a text message "You've already refreshed for today!" to provide feedback.

## Checklist
- [x] Implemented local storage logic to store the refresh state for the day.
- [x] Added `isRefreshDisabled` state to disable the button accordingly.
- [x] Added UI feedback to notify users when they can no longer refresh.
- [x] Tested the functionality across different browsers to ensure local storage consistency.

## Related Issue
Closes #7

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez sir can you please review it and authorize it and merge it

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez sir please review it

**Review by SanchitGeez — APPROVED** [review]

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez  please add the levels in this pr and the gssoc-ext and hactoberfest
and also that you assigned me cause if you dont add they will not count towards my points
can you please add them

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez  the issue was level 3 issue number = #7  
can you please add the correct level label

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez  please add the labels correctly i am not getting any points 
@varshith257 @rahulbamnuya
i fixed issue #7 whish was level 3 please give level 3

**Pull request merged**
