### PR TITLE
✨chatbot added✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
issue #72 has been solved.

@SanchitGeez can you please review this.thank you!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@SanchitGeez can you please review this.

**Comment by SanchitGeez** [comment]
> @SanchitGeez can you please review this.

Sure I'll check it

**Comment by T-Rahul-prabhu-38** [comment]
@SanchitGeez can you please review this.

**Comment by T-Rahul-prabhu-38** [comment]
@SanchitGeez can you please review this.

**Review by SanchitGeez — APPROVED** [review]

**Pull request merged**
