### PR TITLE
Added responsive device feature

### PR DESCRIPTION
**Pull request by Pushpa472**
@SanchitGeez  Please check this...if any error occur then let me known....

### CODE REVIEW

**Comment by SanchitGeez** [comment]
@Pushpa472 I am busy for a couple of days, I saw all your messages and I will merge all the PR's and update the labels in 2 days. DW you will get the points for those

**Comment by Pushpa472** [comment]
@SanchitGeez @partg952 plz merge it

**Comment by Pushpa472** [comment]
@SanchitGeez After how much time does the pull request get accepted for Hacktoberfest can you tell me

**Comment by SanchitGeez** [comment]
> @SanchitGeez After how much time does the pull request get accepted for Hacktoberfest can you tell me

PR is merged...Not sure how much time does it take to reflect on their website.

**Pull request merged**
