### PR TITLE
responsive design added to login and signup page

### PR DESCRIPTION
**Pull request by Sureshwebdeveloper**
responsive design added to the login and signup page

### CODE REVIEW

**Comment by Sureshwebdeveloper** [comment]
I have completed your assigned task but I have noticed one thing you have tried to use the <FaEye/> and <FaEyeSlash/> icons for password enter time show and hides user password but you haven't installed the react icons you are trying to use react-icons package assigned to me I will fix on that

**Review by SanchitGeez — APPROVED** [review]

**Comment by SanchitGeez** [comment]
> I have completed your assigned task but I have noticed one thing you have tried to use the and icons for password enter time show and hides user password but you haven't installed the react icons you are trying to use react-icons package assigned to me I will fix on that I think that is the reason for deployment faile

Thanks. I'll look into it

**Comment by Sureshwebdeveloper** [comment]
If you don't know assign to me I will fix it

**Comment by Sureshwebdeveloper** [comment]
Bro please add  a label the gssocext and hactoberfest badges and add a level as we'll
That is the benifit of contribution me 🥲

**Comment by Sureshwebdeveloper** [comment]
@SanchitGeez  please add gssocext label it will be only add on my contribution 
And also add a level dont forget to do that I hope you doing when ever you see .

**Pull request merged**
