### PR TITLE
Added comment in code

### PR DESCRIPTION
**Pull request by Pushpa472**
@SanchitGeez #59 
before 
image
after
image

### CODE REVIEW

**Comment by SanchitGeez** [comment]
@Pushpa472 Appreciate your efforts but sorry to say these are some extreme overuse of comments...we only need concise comments to explain functional blocks and key components working(try to refer some online articles)......Comments for each line are unnecessary....Kindly Update those

**Comment by Pushpa472** [comment]
@SanchitGeez should i remove it.

**Comment by SanchitGeez** [comment]
> @SanchitGeez should i remove it.

Yes

**Comment by Pushpa472** [comment]
@SanchitGeez again i create pull request can you tell which file should edit.

**Comment by Pushpa472** [comment]
@SanchitGeez  In file should i edit it and again I create pull request. other wise my PR will not be merge
today is last day to submit unmerge PR pending.

**Pull request closed without merging**
